DROP DATABASE IF EXISTS ulsu;
CREATE DATABASE ulsu;
CREATE TABLE Table_1 (Field INT);
CREATE TABLE Table_2 (Field INT);
CREATE TABLE Table_3 (Field NVARCHAR(256));
ALTER TABLE Table_1 ADD column_2 INT;
ALTER TABLE Table_1 DROP COLUMN column_2;
